### ISSUE TITLE
Do you have any examples?

### ISSUE THREAD

**Issue by danvega** [u12206050/gridsome-plugin-algolia#1]
Do you have any examples of using this on a Gridsome blog somewhere? I am a little confused on the fields. Do you have an id in front matter for every single blog post? I don't generate IDs because they aren't being saved anywhere so I wonder if the slug is good enough. 

Also, I don't have a modified date but it seems like I am going to need one because I don't want to regenerate this on every build. Do you have the modified field on every single blog post or just when one changes? 

Thanks for creating this plugin!

**Comment by u12206050** [comment]
The `id` is needed by Algolia to match the same record between builds. WIthout it Algolia won't know which record to update or remove.

The `modified` field is on every post and is an example of a field that is guaranteed to change when something changes, without such a field one would need to include all fields in the `matchFields` option such that all fields are fetched and compared. This however should be a last resort since it can become very heavy if you have say more than 5 fields.

Here is the config of a live example with posts from wordpress:
```
    {
      use: `gridsome-plugin-algolia`,
      options: {
        appId: process.env.ALGOLIA_APP_ID,
        apiKey: process.env.ALGOLIA_API_KEY,
        collections: [
            {
               contentTypeName: 'wordPressPost',
               indexName: 'posts', // Algolia index name
               itemFormatter: (item) => {
                 return {
                   objectID: item.id,
                   title: item.title,
                   slug: item.slug,
                   image: item.featuredMedia && item.featuredMedia.url,
                   modified: item.modified
                 }
               },
               matchFields: ['modified'], // Array<String> required with PartialUpdates
            },
        ],
        enablePartialUpdates: true, // default: false
      },
    },
```

**Comment by danvega** [comment]
Thank you for the response. Sorry if I wasn't clear but how are you generating an id for each blog post?  Are you just using an int or generating some type of GUID? Just trying to figure out how I am going to add this to each of my posts.

**Comment by u12206050** [comment]
I am just using the wordpress id, which is an int. What cms or source are you using?

**Comment by danvega** [comment]
I am just using Markdown... I am going to have to write a generator to add the id it looks like.

**Comment by u12206050** [comment]
You could try and use the slug as your objectID ;)
